### ISSUE TITLE
Is Bitrate Provided?

### ISSUE THREAD

**Issue by seniorm0ment** [jellyfin/mopidy-jellyfin#105]
Using Jellyfin-Mopidy through ncmpcpp, I was curious if bitrate should be working? It could be a configuration issue with ncmpcpp, however I believe it's related to the mopidy plugin not supplying the bitrate information.

**Comment by mcarlton00** [comment]
Looks like it hasn't been added yet, but it should be pretty straightforward.

The Track object reference is here https://docs.mopidy.com/en/latest/api/models/?highlight=models.ref#mopidy.models.Track

And the section in mopidy-jellyfin where we create those is here: https://github.com/jellyfin/mopidy-jellyfin/blob/0279ed08878505d773b5d3ebb2eb20cca99b7142/mopidy_jellyfin/remote.py#L567-L576
