### ISSUE TITLE
Cast/Remote Control Functionality?

### ISSUE THREAD

**Issue by seniorm0ment** [jellyfin/mopidy-jellyfin#112]
Are Jellyfin clients able to "cast" to Mopidy-Jellyfin?
I know they can recognize Kodi, and it can be remote controlled from a device like this.

If not, is this something that can be added? Or is this an issue with Jellyfin server itself and not Mopidy-Jellyfin plugin?

Planning on using this with a raspberry pi so remote control would be huge to be able to just cast instead of needing to feed it through something like mpd then use a seperate app just to control it.

**Comment by mcarlton00** [comment]
That feature is already present and you can cast/control it from a web browser or mobile app.  This is assuming that you're connecting to your server via a method that supports websocket communication.  Going directly to the server via ip:port will work, as well as going through a reverse proxy.  Some reverse proxies need extra options in the config to enable websockets properly, others will handle it implicitly.

![2021-07-27-214222_272x299_scrot](https://user-images.githubusercontent.com/17029228/127250125-5a2dd23d-252f-4a90-93ce-e3f6dec9293a.png)

**Comment by seniorm0ment** [comment]
>connecting to your server

To be clear, you mean connecting to the Jellyfin server? or the phone connecting to the Raspberry running Mopidy?

Also I am using NGINX as my Jellyfin server reverse proxy.

**Comment by mcarlton00** [comment]
Connecting to the Jellyfin server.  How you connect to the device running Mopidy doesn't matter.

nginx works fine, that's what I'm using too.  If you've set it up following our [docs](https://jellyfin.org/docs/general/networking/nginx.html), then you should be all good to go.  If not, there's a location block for websockets that will help things along if you have issues.

**Comment by seniorm0ment** [comment]
Thank you! You can close :)
