### ISSUE TITLE
Configure as shared DLNA device (renderer)

### ISSUE THREAD

**Issue by Tropaion** [jellyfin/mopidy-jellyfin#113]
I successfully set up mopidy-jellyfin for one user for music rendering and it works nicely.
But I have a few locations where I need it as an shared device, how do I set this up?
I searched everywhere, but didn't find anything about that.

**Comment by mcarlton00** [comment]
As far as I'm aware, there's currently no way for us to configure a Jellyfin client as a shared device.  You'd need to find something else that would implement the DLNA spec in some way.

This _may_ help you, but admittedly it's outside my use case so I've never tried it personally.  https://mopidy.com/ext/dleyna/  I imagine there's also more programs purpose built for DLNA, but I don't have much experience with them.
