### ISSUE TITLE
Will this still work with Emby? 

### ISSUE THREAD

**Issue by Axachi** [jellyfin/mopidy-jellyfin#116]
Sorry but I was looking for this and came across an old post form @feerlessleadr. And was wondering if this project still supports Emby. I have tried and I get no Library when browsing. only Music, witch contains noting :)

**Comment by mcarlton00** [comment]
Officially, no I don't support emby servers.  I don't have an emby server to test against so if it works at all then it's mostly be happy accident.  I suspect that the api's have diverged enough that supporting both won't be super straightforward.  You may want to look at https://github.com/xsteadfastx/mopidy-emby, which is the ancestor of this project, but I'm not sure what the current status of it is.
