### ISSUE TITLE
NixOS pkg (derivation) request

### ISSUE THREAD

**Issue by Deep-Six** [jellyfin/mopidy-jellyfin#122]
Hello,

I'm wondering if it'd be possible for someone to package this for the NixOS Linux distribution. I unfortunately still too new to Nix to do it myself but will continue to learn in hopes of contributing if it's not completed before then.

**Comment by gador** [comment]
Hi,

this is already packaged in nixos.
See https://search.nixos.org/packages?channel=unstable&show=mopidy-jellyfin&from=0&size=50&sort=relevance&type=packages&query=Mopidy-jellyfin

Note: this is not in 21.11 but in unstable

**Comment by Deep-Six** [comment]
@gador Thanks very kindly! I'll close it promptly!

**Comment by mcarlton00** [comment]
I had no idea this was repackaged for NixOS, so that's neat.  Thanks for sharing!
