### ISSUE TITLE
Change Music Library Viewing

### ISSUE THREAD

**Issue by JBlocklove** [jellyfin/mopidy-jellyfin#131]
Is there a way to sort the music library by different things? Currently when I navigate to my Jellyfin music in the browser in `ncmpcpp` I only get the album artists, but I would like to be able to also view my library by albums or even individual songs. Is there currently any way to do that? If so would I be able to have multiple options for the view, or would I need to adjust my config and re-run `mopidy` every time?

Currently, here is my jellyfin config:
```
[jellyfin]
hostname = <redacted>
username = <redacted>
password = <redacted>
libraries = "Music"
albumartistsort = True
```

**Comment by mcarlton00** [comment]
This would be more of a question for the ncmpcpp project.  Mopidy extensions like this one just provide data, the frontend clients decide how to display that data.  In theory it should be possible, as mopidy-iris has an album view, but in my experience it's very slow and I'm not sure if there's any way to replicate that behavior in ncmpcpp.
