### ISSUE TITLE
How to define baseurl?

### ISSUE THREAD

**Issue by accad** [jellyfin/mopidy-jellyfin#47]
This is it really, I am not sure where/how to define the baseUrl of my Jellyfin instance

If I use the hostname = http://server/base for example, I get an error 

Exception: Cant connect to Jellyfin API

If I remove the /base part, I get the same error 

I have been reading remote.py and I cannot find the code of where to define this

Help please? :)

Thank you

**Comment by mcarlton00** [comment]
I'd actually never tested this before.  I forget that baseurl exists sometimes.  It's definitely broken right now.  So the root issue right now is that the baseurl is just getting stripped from the hostname when making api calls, and that's happening in this line:

https://github.com/jellyfin/mopidy-jellyfin/blob/0efe15b35644209a2ec127b67973f8aeb924eee8/mopidy_jellyfin/remote.py#L147

Changing how that's handled does make it behave better, but still not fully functional so a bit more rework is needed
