### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by PNRxA** [jellyfin/mopidy-jellyfin#81]
Is it possible to add a Dockerfile + dockerhub to this project to make it easy to deploy? Would be useful for Unraid/NAS setups.

Also as a side note, would it be possible to deploy this on the same server as Jellyfin from the plugins menu in the future?

**Comment by mcarlton00** [comment]
Somebody else on the team had actually started on a docker image for this, but afaik it never got operational.  I just haven't had the time to look at that project and figure out what the issue was.

https://github.com/Artiume/docker-mopidy

**Comment by PNRxA** [comment]
I've started testing a docker image at https://github.com/PNRxA/docker-mopidy
I've just added it in the pip configuration with the intention of editing the config in the /config/mopidy.conf file

**Comment by PNRxA** [comment]
@mcarlton00 can confirm my fork works, I've added it to dockerhub https://hub.docker.com/r/pnrxa/mopidy
